services:
  tubearchivist:
    container_name: tubearchivist
    image: docker.io/bbilly1/tubearchivist:v0.4.10
    restart: unless-stopped
    volumes:
      - /etc/localtime:/etc/localtime:ro

      - data-tubearchivist:/cache

      - media-youtube:/youtube
    env_file:
      - path: /etc/broad/tubearchivist/secrets.env
        required: false
    environment:
      ES_URL: http://tubearchivist-es:9200
      REDIS_HOST: tubearchivist-redis
      TA_HOST: tubearchivist.beannet.app
      TA_USERNAME: admin
      TA_ENABLE_AUTH_PROXY: true
      TA_AUTH_PROXY_USERNAME_HEADER: HTTP_REMOTE_USER
      TA_AUTH_PROXY_LOGOUT_URL: beannet.app
    healthcheck:
      test: curl -f http://localhost:8000 || exit 1
    labels:
      autoheal: true

      io.containers.autoupdate: registry

      wud.watch: true
      wud.tag.include: '^v\\d+\\.\\d+\\.\\d+$$$$'

      traefik.enable: true
      traefik.http.services.tubearchivist.loadbalancer.server.port: 8000

      kuma.__service:
      kuma.__internal:
      kuma.__external:

      homepage.group: Main
      homepage.name: Tubearchivist
      homepage.icon: tube-archivist
      homepage.href: https://tubearchivist.beannet.app
      homepage.siteMonitor: https://tubearchivist.beannet.app
      homepage.widget.type: tubearchivist
      homepage.widget.url: http://tubearchivist:8000
      homepage.widget.key: "{{HOMEPAGE_FILE_TUBEARCHIVIST_KEY}}"
    depends_on:
      - tubearchivist-es
      - tubearchivist-redis

  tubearchivist-redis:
    container_name: tubearchivist-redis
    image: docker.io/redis/redis-stack-server:7.4.0-v0
    restart: unless-stopped
    volumes:
      - /etc/localtime:/etc/localtime:ro

      - data-tubearchivist-redis:/data
    labels:
      kuma.__service:
      kuma.__internal:
    depends_on:
      - tubearchivist-es

  tubearchivist-es:
    container_name: tubearchivist-es
    image: docker.io/elasticsearch:8.15.3
    restart: unless-stopped
    volumes:
      - /etc/localtime:/etc/localtime:ro

      - data-tubearchivist-es:/usr/share/elasticsearch/data
    env_file:
      - path: /etc/broad/tubearchivist/secrets.env
        required: false
    environment:
      ES_JAVA_OPTS: -Xms1g -Xmx1g
      xpack.security.enabled: true
      discovery.type: single-node
      path.repo: /usr/share/elasticsearch/data/snapshot
    labels:
      kuma.__service:
      kuma.__internal:

volumes:
  data-tubearchivist:
    name: data-tubearchivist
  data-tubearchivist-redis:
    name: data-tubearchivist-redis
  data-tubearchivist-es:
    name: data-tubearchivist-es
